name: Fetch Dependencies

on:
  schedule:
    - cron: '20 */2 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: generate
  cancel-in-progress: true

jobs:
  fetchdeps:
    name: Fetch Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Build and Run Generator
        run: dotnet run --project Generator/Generator.csproj -c Release -- LemonLoader MelonLoader.UnityDependencies.China main
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
